name: "Lint"

on:
  push:
    branches:
      - '*'
    paths:
      - '**/*.tf'
      - '**/*.hcl'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - run: terraform fmt -check -recursive

      - run: terraform init -backend=false

      - run: terraform validate -no-color

      - uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v5

      - run: tflint --version

      - run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - run: tflint -f compact

      - uses: terraform-docs/gh-actions@v1
