name: "Release"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write # creates labels, has been removed from "pull-requests" permission

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release-type: terraform-module
