name: "Test"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.7.0"

      - uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-oidc/providers/github-oidc
          service_account: github-oidc@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}
          location: ${{ vars.GOOGLE_REGION }}
          cluster_name: ${{ vars.GKE_CLUSTER_NAME }}

      - run: terraform init

      - run: terraform test
        env:
          GOOGLE_PROJECT: ${{ vars.GOOGLE_PROJECT }}
          GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}
